name: Bug Report
description: Create a report to help us improve
labels: ["Type: Bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Gloo Edge Version
      description: What version of Gloo Edge are you using?
      options:
        - 1.10.x (beta)
        - 1.9.x (latest stable)
        - 1.8.x
        - 1.7.x
        - 1.6.x
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      placeholder: Add a clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the bug
      placeholder: |
        1. kube apply '...'
        2. curl '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: When I performed x, I expected y to happen
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: |
        - Kubernetes version
